### PR TITLE
Fix marshaling nested arrays of tables

### LINKED ISSUE #369: Marshalling fails for nested arrays of tables
**Describe the bug**
Marshalling produces an error:
```
marshalling error: unsupported value type *toml.Tree: key = "Control"
```

**To Reproduce**
```go
tree, err := toml.Load(`
combinations = [
	[{ key = "Control" }, { key = "Q" }],
	[{ key = "Escape" }],
]
`)

if err != nil {
	fmt.Println("loading error:", err)
}

_, err = tree.Marshal()
if err != nil {
	fmt.Println("marshalling error:", err)
}
```
**Expected behavior**
There is no error when loading TOML data, so marshalling should work.

**Versions**
 - go-toml: last version of master (323fe5d)
 - go: 1.14
 - operating system: Linux

**Additional context**
Unmarshalling works:

```go
type Button struct {
	Key string
}

type Action struct {
	Combinations [][]Button
}

var action Action
err = tree.Unmarshal(&action)
if err != nil {
	fmt.Println("unmarshalling error:", err)
}

fmt.Println(action)
```

Output:
```
{[[{Control} {Q}] [{Escape}]]}
```

### PR DESCRIPTION
**Pull request by x-hgg-x**
This PR fixes marshaling for nested arrays of tables by adding support for inline tables.

Fixes #369.

### CODE REVIEW

**Comment by pelletier** [comment]
Thank you for the patch, looks good! Any chance you might fix the conflicts before I merge please?

File: parser_test.go [hunk 1]
```diff
@@ -919,10 +919,10 @@ func TestTomlValueStringRepresentation(t *testing.T) {
 		{"\b\t\n\f\r\"\\", "\"\\b\\t\\n\\f\\r\\\"\\\\\""},
 		{"\x05", "\"\\u0005\""},
 		{time.Date(1979, time.May, 27, 7, 32, 0, 0, time.UTC), "1979-05-27T07:32:00Z"},
-		{[]interface{}{"gamma", "delta"}, "[\"gamma\",\"delta\"]"},
+		{[]interface{}{"gamma", "delta"}, "[\"gamma\", \"delta\"]"},
 		{nil, ""},
 	} {
-		result, err := tomlValueStringRepresentation(item.Value, "", "", OrderPreserve, false)
+		result, err := tomlValueStringRepresentation(item.Value, "", "", OrderAlphabetical, false)
```
Comment (x-hgg-x) [inline parser_test.go:925]: Default is OrderAlphabetical.

**Comment by pelletier** [comment]
Thank you!
