### PR TITLE
fix issue #339

### LINKED ISSUE #339: Unexpected result when nested struct
**Describe the bug**
For nested struct，if there are attributes with same name, parse result is not expected.

**To Reproduce**
```
type Server struct {
    Name string `toml:"name" default:"noname"`
    Inter2 Inter2 `toml:"inter2"`
}

type Inter2 struct {
    Name         string
    Age          int
    InterStruct2 InterStruct2
}

type InterStruct2 struct {
    Test string
    Name string
    Age  int
}
var server Server

err := toml.Unmarshal([]byte(`name = "123"

[inter2]
	name = "inter2"
	age = 222`), &server)
```

**Expected behavior**
Expected value of server:
```
{Name:"123", Inter2:{Name:"inter2", Age:222, InterStruct2:{Test:"", Name:"", Age:0}}}
```

but got:
```
{Name:"123", Inter2:{Name:"inter2", Age:222, InterStruct2:{Test:"", Name:"inter2", Age:222}}}
```

**Versions**
 - go-toml: master
 - go: 1.13.8
 - operating system: Windows

### PR DESCRIPTION
**Pull request by AllenX2018**
**Issue:** #339

This pr try to fix #339. And this bug seems to be introduced by #281.

### CODE REVIEW

File: marshal_test.go [hunk 1]
```diff
@@ -4,6 +4,7 @@ import (
 	"bytes"
 	"encoding/json"
 	"fmt"
+	"github.com/BurntSushi/toml"
```
Comment (pelletier) [inline marshal_test.go]: I think this tests the wrong library :)

Comment (AllenX2018) [reply marshal_test.go]: Oops...Why would I get that wrong :(
